### ISSUE TITLE
WGUI Times out on kubernetes

### ISSUE THREAD

**Issue by Slyke** [ngoduykhanh/wireguard-ui#156]
When navigating to `10.1.1.233:5000` Chrome reports `ERR_CONNECTION_TIMED_OUT`. I use a similar setup for just Wireguard by itself in another deployment, and many other webapps with similar services.

Pod logs:
```
Wireguard UI
App Version     : development
Git Commit      : N/A
Git Ref         : N/A
Build Time      : 02-13-2022 11:15:09
Git Repo        : https://github.com/ngoduykhanh/wireguard-ui
Authentication  : true
Bind address    : 0.0.0.0:5000
Email from      : you@yourdomain.tld
Email from name : your name
⇨ http server started on [::]:5000
```

Here's my K8s yaml:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wireguard-ui
  name: wireguard-ui
  namespace: my-namespace
spec:
  progressDeadlineSeconds: 10
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: wireguard-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wireguard-ui
    spec:
      containers:
      - env:
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: wireguard-ui-secret
              key: sendgridApiKey
        - name: EMAIL_FROM_ADDRESS
          valueFrom:
            secretKeyRef:
              name: wireguard-ui-secret
              key: emailFromAddress
        - name: EMAIL_FROM_NAME
          valueFrom:
            secretKeyRef:
              name: wireguard-ui-secret
              key: emailFromName
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: wireguard-ui-secret
              key: sessionSecret
        - name: WGUI_USERNAME
          valueFrom:
            secretKeyRef:
              name: wireguard-ui-secret
              key: wguiUsername
        - name: WGUI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wireguard-ui-secret
              key: wguiPassword
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: ServerIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: ngoduykhanh/wireguard-ui:latest
        imagePullPolicy: IfNotPresent
        name: wireguard-ui
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        - containerPort: 51820
          name: vpnudp
          protocol: UDP
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
        volumeMounts:
        - mountPath: /app/db
          name: wireguard-ui-db
        - mountPath: /etc/wireguard
          name: wireguard-ui-wg
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 3
      volumes:
      - name: wireguard-ui-db
        persistentVolumeClaim:
          claimName: wireguard-ui-db-pvc
      - name: wireguard-ui-wg
        persistentVolumeClaim:
          claimName: wireguard-ui-wg-pvc
---
apiVersion: v1
kind: Secret
metadata:
  name: wireguard-ui-secret
  namespace: my-namespace
type: Opaque
stringData:
  sendgridApiKey: apiKey
  emailFromAddress: "you@yourdomain.tld"
  emailFromName: "your name"
  sessionSecret: 64characterSecret
  wguiUsername: yourUsername
  wguiPassword: yourPassword
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: my-namespace
  labels:
    app: wireguard-ui
  name: wireguard-ui-db-pvc
spec:
  storageClassName: ""
  volumeName: wireguard-ui-db-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: my-namespace
  labels:
    app: wireguard-ui
  name: wireguard-ui-wg-pvc
spec:
  storageClassName: ""
  volumeName: wireguard-ui-wg-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wireguard-ui
  name: wireguard-ui
  namespace: my-namespace
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    protocol: TCP
    port: 5000
  - name: http2
    protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: wireguard-ui
  loadBalancerIP: 10.1.1.233
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wireguard-ui
  name: wireguard-ui
  namespace: my-namespace
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  externalTrafficPolicy: Local
  ports:
  - name: wireguard-udp
    protocol: UDP
    port: 51820
  selector:
    app: wireguard-ui
  loadBalancerIP: 10.1.1.233
  type: LoadBalancer
```

Pod describe:
```
Name:         wireguard-ui-5d4f4f4f9-v7ptr
Namespace:    my-namespace
Priority:     0
Node:         k8snode3/10.1.2.3
Start Time:   Sun, 13 Feb 2022 11:15:08 +0000
Labels:       app=wireguard-ui
              pod-template-hash=5d4f4f4f9
Annotations:  <none>
Status:       Running
IP:           10.244.2.154
IPs:
  IP:           10.244.2.154
Controlled By:  ReplicaSet/wireguard-ui-5d4f4f4f9
Containers:
  wireguard-ui:
    Container ID:   docker://f8f9d270751c040067142b9081a18f372361ef473eb415a04fe8d579514efbb5
    Image:          ngoduykhanh/wireguard-ui:latest
    Image ID:       docker-pullable://ngoduykhanh/wireguard-ui@sha256:7719cfd82e5f22d293460430efcc625a06b3fe09f1a5036989c9104dfc5b4575
    Ports:          5000/TCP, 51820/UDP
    Host Ports:     0/TCP, 0/UDP
    State:          Running
      Started:      Sun, 13 Feb 2022 11:15:09 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  256Gi
    Requests:
      cpu:     10m
      memory:  32Mi
    Environment:
      SENDGRID_API_KEY:    <set to the key 'sendgridApiKey' in secret 'wireguard-ui-secret'>    Optional: false
      EMAIL_FROM_ADDRESS:  <set to the key 'emailFromAddress' in secret 'wireguard-ui-secret'>  Optional: false
      EMAIL_FROM_NAME:     <set to the key 'emailFromName' in secret 'wireguard-ui-secret'>     Optional: false
      SESSION_SECRET:      <set to the key 'sessionSecret' in secret 'wireguard-ui-secret'>     Optional: false
      WGUI_USERNAME:       <set to the key 'wguiUsername' in secret 'wireguard-ui-secret'>      Optional: false
      WGUI_PASSWORD:       <set to the key 'wguiPassword' in secret 'wireguard-ui-secret'>      Optional: false
      NODE_NAME:            (v1:spec.nodeName)
      POD_NAME:            wireguard-ui-5d4f4f4f9-v7ptr (v1:metadata.name)
      POD_NAMESPACE:       my-namespace (v1:metadata.namespace)
      ServerIP:             (v1:status.podIP)
    Mounts:
      /app/db from wireguard-ui-db (rw)
      /etc/wireguard from wireguard-ui-wg (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-v5rg9 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  wireguard-ui-db:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  wireguard-ui-db-pvc
    ReadOnly:   false
  wireguard-ui-wg:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  wireguard-ui-wg-pvc
    ReadOnly:   false
  kube-api-access-v5rg9:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  12m   default-scheduler  Successfully assigned my-namespace/wireguard-ui-5d4f4f4f9-v7ptr to k8snode3
  Normal  Pulled     12m   kubelet            Container image "ngoduykhanh/wireguard-ui:latest" already present on machine
  Normal  Created    12m   kubelet            Created container wireguard-ui
  Normal  Started    12m   kubelet            Started container wireguard-ui
```
