### ISSUE TITLE
WG Status

### ISSUE THREAD

**Issue by SAOPP** [ngoduykhanh/wireguard-ui#185]
Hi!

Testing comination linuxserver container of wg with ui:

Here is my test stack:

```
version: "2.1"

networks:
  proxy:
    external: true

services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    networks:
      - proxy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PEERS=0
    volumes:
      - /docker_storage/wireguard:/config:ro
    restart: always
    labels:
      - traefik.enable=true
      - traefik.udp.routers.wireguard.entrypoints=wireguard
      - traefik.udp.routers.wireguard.service=wireguard
      - traefik.udp.services.wireguard.loadbalancer.server.port=51820
  wgui:
    image: ngoduykhanh/wireguard-ui
    container_name: wireguard-ui
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - /docker_storage/wireguard:/etc/wireguard
      - /docker_storage/wireguard:/app/db
    depends_on:
      - wireguard
    restart: always
```
The status page is always empty when client is connected, where is my mistake? Thanks in advance!
