### ISSUE TITLE
Please update documentation and/or provide working compose example

### ISSUE THREAD

**Issue by zilexa** [ngoduykhanh/wireguard-ui#186]
The current example is not really a great one since it misses essential elements:

- `image` is commented out, that makes no sense? It will never work with Compose without image. 
- `SMTP_AUTH_TYPE` possible values are not documented. People created issues because of this. That's how I found out value should be LOGIN when you need authentication. 
- Ports are missing in the example. Perhaps due to host network this can work? I'm no expert. But I couldn't find which port is used in the readme.md! It should at least be documented. I used Portainer log to figure it out. Why make it so hard?

Here is a better one:
```
  vpn-portal:
    container_name: vpn-portal
    image: ngoduykhanh/wireguard-ui:latest
    restart: always
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      SMTP_HOSTNAME: $SMTP
      SMTP_PORT: $SMTPPORT
      SMTP_USERNAME: $SMTPUSER
      SMTP_PASSWORD: $SMTPPASS
      SMTP_AUTH_TYPE: LOGIN
      EMAIL_FROM_ADDRESS: $RECIPIENT
      EMAIL_FROM_NAME: $SMTPUSER
      SESSION_SECRET: $VPNSECRET
    logging:
      driver: json-file
      options:
        max-size: 15m
    volumes:
      - $DOCKERDIR/vpn-portal/db:/app/db
      - /etc/wireguard:/etc/wireguard  
    ports:
      - 5000:5000
```
