### ISSUE TITLE
How configure with linuxserver/wireguard

### ISSUE THREAD

**Issue by Andrysky** [ngoduykhanh/wireguard-ui#197]
i try to link it with linuxserver/wireguard but it doesn't work(

```
---
version: "2.1"
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Riga
      - SERVERURL=<ip> #wireguard.domain.com #optional
      - SERVERPORT=51833 #optional
#      - PEERS=3 #optional
#      - PEERDNS=auto #optional
      #- INTERNAL_SUBNET=10.13.13.0 #optional
#      - INTERNAL_SUBNET=192.168.11.0
#      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - ./volumes/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51822:51822/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wgui
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET
      - WGUI_USERNAME=andry
      - WGUI_PASSWORD=${WIREGUARD_UI_PASSWORD}
      - WG_CONF_TEMPLATE
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./volumes/wireguard-ui/db:/app/db
      - ./volumes/config:/etc/wireguard
    restart: unless-stopped
```

**Comment by theobarrague** [comment]
Here my workaround :
```
FROM debian:bullseye-slim

RUN apt-get update && \
    apt-get -y install wireguard iptables iproute2 inotify-tools && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /etc/entrypoint.sh

CMD ["sh", "/etc/entrypoint.sh"]
```
```
#!/usr/bin/env sh

while true; do 
  wg-quick down wg0
  wg-quick up wg0
  inotifywait -e close_write /etc/wireguard/wg0.conf >/dev/null 2>&1
  sleep 5s
done

exit 1
```

**Comment by den-kuz** [comment]
Here's my solution, but i liked @theobarrague's too

Dockefile:
```
FROM linuxserver/wireguard:latest

RUN apt-get update && apt-get install incron && apt-get clean
RUN echo root > /etc/incron.allow
RUN touch /var/spool/incron/root && chown root:root /var/spool/incron/root

RUN touch /config/wg0.conf
RUN echo '/config/wg0.conf IN_MODIFY wg-quick down wg0 && wg-quick up wg0 && echo "$$(date) Server restarted" >> /server_log.log' >> /var/spool/incron/root

ENTRYPOINT ["/bin/sh", "-c" , "service incron restart && /init"]
```

docker-compose.yml:
```
version: "3.8"
services:
  wireguard:
    container_name: wireguard
    hostname: wireguard
    build:
      context: ./wireguard
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 51820:51820/udp
    environment:
      - LOG_CONFS=false
      - SERVERURL=wg.some.domain
      - TZ=Europe/Moscow
    restart: unless-stopped
    volumes:
      - /lib/modules:/lib/modules
      - ./wireguard/config/:/config
```

**Comment by wa-devops** [comment]
Here is working setup:

---
version: "3.7"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
#      - SERVERURL=wireguard.kafana.dev #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
      - 0.0.0.0:5000:5000
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  wg:
#    build: .
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wgui
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard #this uses networking from wireguard server container
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET
      - WGUI_USERNAME=username
      - WGUI_PASSWORD=urpasshere
      - WG_CONF_TEMPLATE
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./config:/app/db
      - ./config:/etc/wireguard

----
###
Also make sure to add:
On Gui Server section:

Add  post up:

iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

Post down:

iptables -D FORWARD -i %i -j ACCEPT; iptables -D FOR -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADEWARD

**Comment by nikdjukic** [comment]
This worked for me. Even shows client status :)

```yaml
version: "3.7"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
#      - SERVERURL=wireguard.kafana.dev #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
      - 0.0.0.0:5000:5000
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  wg:
#    build: .
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wgui
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET
      - WGUI_USERNAME=durbok
      - WGUI_PASSWORD=urpasshere
      - WG_CONF_TEMPLATE
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./config:/app/db
      - ./config:/etc/wireguard
```
On Gui Server section:

Add  post up:

```bash
iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
```
Post down:
```bash
iptables -D FORWARD -i %i -j ACCEPT; iptables -D FOR -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADEWARD
```
