### ISSUE TITLE
arm64 docker image

### ISSUE THREAD

**Issue by zachberger** [ngoduykhanh/wireguard-ui#21]
Hi there,

I'd be interested in an arm64 docker image for my raspberry pi wireguard installation. I see there is already an arm64 binary.

Thanks!

**Comment by babico** [comment]
> @ngoduykhanh How could I run this with docker in my raspberry pi 3? I downloaded the source code, and then build the docker image, but when I tried to run it, it returned this error: `standard_init_linux.go:219: exec user process caused: exec format error`
> 
> If I check the image, it sais: `Build | Docker 20.10.6 on linux, arm`
> 
> So not sure what I am doing wrong.

I got similar error to at my Oracle ARM instance.
`standard_init_linux.go:228: exec user process caused: exec format error`

**Comment by ngoduykhanh** [comment]
I pushed a docker image `ngoduykhanh/wireguard-ui:latest-arm64` that could work on ARM arch.

**Comment by florianthonig** [comment]
Thanks,
I got it working on my Raspberry Pi 4 by doing:
- changing the image in docker-compose.yaml to ```ngoduykhanh/wireguard-ui:latest-arm64```
- changing ```TARGETARCH``` in Dockerfile to ```arm64```

Then just running ```docker-compose build``` and ```docker-compose up``` got it working for me.

**Comment by chetbox** [comment]
I'm using a 32-bit ARM OS (Raspberry Pi OS) but I can't run the docker image.

```
 $ sudo docker run -ti --rm --platform linux/arm/v7 ngoduykhanh/wireguard-ui
Unable to find image 'ngoduykhanh/wireguard-ui:latest' locally
latest: Pulling from ngoduykhanh/wireguard-ui
Digest: sha256:aea0f09c08733f9c8ea6da3cde28a8e593ee141da6a1bff9a75bb930ae211a91
Status: Image is up to date for ngoduykhanh/wireguard-ui:latest
WARNING: image with reference ngoduykhanh/wireguard-ui was found but does not match the specified platform: wanted linux/arm/v7, actual: linux/amd64
docker: Error response from daemon: image with reference ngoduykhanh/wireguard-ui was found but does not match the specified platform: wanted linux/arm/v7, actual: linux/amd64.
```

It seems like it's always pulling the `amd64` image.

**Comment by isac322** [comment]
I published arm64, amd64, armv7 images on https://hub.docker.com/r/isac322/wireguard-ui. The publish pipeline is fully automated using Dependabot. Please checkout repo https://github.com/isac322/docker_image_wireguard-ui

**Comment by codestation** [comment]
> I pushed a docker image `ngoduykhanh/wireguard-ui:latest-arm64` that could work on ARM arch.

The image is wrongly tagged as amd64, so it doesn't work with Docker Swarm.

```
$ docker image inspect ngoduykhanh/wireguard-ui:latest-arm64 -f '{{.Architecture}}'
amd64
```

**Comment by mojothemonkey2** [comment]
Yes, I noticed probs too with the arm image.
It runs the webUI fine, but cant open a shell, eg:
```
$ docker run --rm -it --entrypoint='/bin/sh' ngoduykhanh/wireguard-ui:latest-arm64 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /bin/sh: exec format error
```

built it myself on arm64, and did not get this problem.
```
docker build -t mojothemonkey/wireguard-ui:latest --build-arg TARGETARCH=arm64 . 
```

**Comment by francescor** [comment]
working arm image will be really appreciated, how is the situation? 

```
$ docker pull ngoduykhanh/wireguard-ui:latest-arm64
Error response from daemon: manifest for ngoduykhanh/wireguard-ui:latest-arm64 not found: manifest unknown: manifest unknown
```

**Comment by mojothemonkey2** [comment]
@francescor looks like this is fixed in the more recent images.
so you can just use 'latest' image and it will pull the correct image for amr64 arch.

full eg compose, that works on my arm64 box:
```
services:
  wg:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wgui
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET
      - WGUI_USERNAME=alpha
      - WGUI_PASSWORD=this-unusual-password
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=false
      - WGUI_MANAGE_RESTART=false
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - /etc/wireguard:/etc/wireguard
```
