### ISSUE TITLE
fail to start container

### ISSUE THREAD

**Issue by redfirebrooks** [ngoduykhanh/wireguard-ui#286]
OS : debian bullseyes raspberry 4
Docker version 20,2,20

i tried to run fireguard ui with docker but it fails to start.

docker-compose.yml :
```
version: "3"

services:
  wg:
    #build: .
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wgui
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET
      - WGUI_USERNAME=user
      - WGUI_PASSWORD=mypassword
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=false
      - WGUI_MANAGE_RESTART=false
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - /home/pi/docker/wireguard/config:/etc/wireguard
```

Error logs:
```
exec ./init.sh: exec format error
exec ./init.sh: exec format error
exec ./init.sh: exec format error
```
