### ISSUE TITLE
Docker without - network_mode: host

### ISSUE THREAD

**Issue by andycandy-de** [ngoduykhanh/wireguard-ui#299]
Hello
I want to run this project in a docker container. I prefer to use a internal network and to expose the wanted ports. So I tried to adjust the docker-compose and applied some configurations from the project https://github.com/WeeJeWel/wg-easy

```
version: "3"

services:
  wg:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - "51820:51820/udp"
      - "5000:5000/tcp"
    environment:
      - WGUI_USERNAME=anyuser
      - WGUI_PASSWORD=anypw
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - ./wireguard:/etc/wireguard
```

Is this configuration correct? I cannot access the internet when I connect a client with the server. What could be wrong?
Is the wireguard volume mapping required? I am not sure but I suppose it is unnecessary.

**Comment by alex27riva** [comment]
Hi, it seems that the volume mapping is incorrect, it should be `/etc/wireguard:/etc/wireguard`.
Also I have a similar issue deploying this container using Ansible, the client is not receiving data from the server.

**Comment by andycandy-de** [comment]
@alex27riva I think the mapping `/etc/wireguard:/etc/wireguard` is just necessary when the `network_mode` is set to `host`.

**Comment by alex27riva** [comment]
> @alex27riva I think the mapping `/etc/wireguard:/etc/wireguard` is just necessary when the `network_mode` is set to `host`.

Yeah, I think you're right.
Also, what host system are you using?

**Comment by andycandy-de** [comment]
It s a alpine linux with docker

```
[#] ip link set mtu 1450 up dev wg0
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
sysctl: error setting key 'net.ipv4.conf.all.src_valid_mark': Read-only file system
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wg0
```

I checked the container logs and I saw the sysctl error. This option is already set in my docker-compose file. Does the `wireguard-ui` logic try to set this?

**Comment by andycandy-de** [comment]
But I am getting the same error when I am running the container with network_mode: host

**Comment by andycandy-de** [comment]
OK, I found out following facts. I set the extra allowed ips of a client to 0.0.0.0/0. When this is set the sysctl error ocours. Otherwise it doesn't set the net.ipv4.conf.all.src_valid_mark and the interface wg0 is created.
When I start the container with privilege enabled the container is able to create the wg0 interface although the  extra allowed ips.

```
version: "3"

services:
  wg:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - "51820:51820/udp"
      - "5000:5000/tcp"
    environment:
      - WGUI_USERNAME=anyuser
      - WGUI_PASSWORD=anypw
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
    privileged: true
```

The volume mapping of wireguard is unnecessary. I veryified it. But I am still not able to access the internet with the client. Any ideas?

**Comment by andycandy-de** [comment]
OK, there s a little issue with the wg0.conf file. It's not generated at container start so I have to click to `Apply config` in the UI after each start. So I add the mapping again. Could be removed when an app start auto generate the config.

I am not sure if `net.ipv4.conf.all.src_valid_mark=1` is needed. I this `wg-quick` enables it when it is necessary, which explains the error above.

So my current `docker-compose.yml` looks like this
```
version: "3"

services:
  wg:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - "51820:51820/udp"
      - "5000:5000/tcp"
    environment:
      - WGUI_USERNAME=anyuser
      - WGUI_PASSWORD=anypw
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - ./config:/etc/wireguard
    privileged: true
```

I solved my internet problem in the server configuration view by setting `Post Up Script`and `Post Down Script`
Post Up Script: `iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE`
Post Down Script: `iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE`

I hope that can help anyone (@alex27riva )

**Comment by alex27riva** [comment]
Now it works for me too, thanks @andycandy-de, sigonava press "Apply config".
I also share my configuration (I use Ansible) which might be useful to someone else.
```yml
---
- name: Configure Wireguard container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: 'ngoduykhanh/wireguard-ui:latest'
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.ip_forward: '1'
      net.ipv4.conf.all.src_valid_mark: '1'
    ports:
      - "{{ wg_server_port }}:{{ wg_server_port }}/udp" # 51820:51820/udp
      - "{{ wireguard_port }}:5000/tcp" # 5000:5000/tcp
    env:
      WGUI_USERNAME: "{{ wgui_username }}"
      WGUI_PASSWORD: "{{ wgui_password }}"
      WGUI_ENDPOINT_ADDRESS: "{{ ddns_endpoint }}"
      WGUI_SERVER_LISTEN_PORT: "{{ wg_server_port }}" # 51820
      WGUI_SERVER_POST_UP_SCRIPT: "{{ post_up }}" # same as previous post
      WGUI_SERVER_POST_DOWN_SCRIPT: "{{ post_down }}" # same as previous post
      WGUI_DNS: "{{ pihole_ip }}"
      WGUI_MANAGE_START: 'true'
      WGUI_MANAGE_RESTART: 'true'
    volumes:
      - "{{ docker_dir }}/wireguard/db:/app/db"
      - "{{ docker_dir }}/wireguard/config:/etc/wireguard"
    restart_policy: unless-stopped
    privileged: true

```
