### ISSUE TITLE
wireguard not listening on port 51820

### ISSUE THREAD

**Issue by Janevski** [ngoduykhanh/wireguard-ui#301]
I am using wireguard-ui in docker and i can't get it to work, because when the client is trying to connect to UDP 51820, the server responds with ICMP port unreachable, which means nothing is listening there.
I've checked on the server and within the wgui container, nothing is listening on UDP 51820. And there is no wg0 interface.

19:00:39.833454 eth0  In  IP 37.25.86.42.61773 > 5.75.196.218.51820: UDP, length 148
19:00:39.833517 eth0  Out IP 5.75.196.218 > 37.25.86.42: ICMP 5.75.196.218 udp port 51820 unreachable, length 184

My docker-compose is as follows:
```
...
  wgui:
    build: build/wireguard-ui
    image: wireguard-ui:latest
    container_name: wgui
    hostname: wgui
    restart: always
    #logging:
    #    driver: none
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:9992"
    #logging:
    #  options:
    #    max-size: "100m"
    #    max-file: "3"
    deploy:
      replicas: 1
      resources:
        limits:
          #cpus: '2'
          memory: ${ENV_RAM_LIMIT}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TZ=${ENV_TIMEZONE}
      - SENDGRID_API_KEY=${ENV_SENDGRID_API_KEY}
      - EMAIL_FROM_ADDRESS=${ENV_EMAIL_FROM_ADDRESS}
      - EMAIL_FROM_NAME=${ENV_EMAIL_FROM_NAME}
      - SESSION_SECRET=${ENV_SESSION_SECRET}
      - WGUI_USERNAME=${ENV_WGUI_USERNAME}
      - WGUI_PASSWORD=${ENV_WGUI_PASSWORD}
      #- WG_CONF_TEMPLATE=${ENV_WG_CONF_TEMPLATE}
      - WGUI_MANAGE_START=false
      - WGUI_MANAGE_RESTART=false
    volumes:
       - ${ENV_DIR}/${ENV_PROJECT}/vpn_db:/app/db
       - ${ENV_DIR}/${ENV_PROJECT}/vpn_config:/etc/wireguard
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    network_mode: host
    #depends_on:
    #  - db
    ...
```

Description:	Ubuntu 22.04.1 LTS
Docker version 20.10.22, build 3a2c30b
docker-compose version 1.29.2, build 5becea4c
wireguard-tools v1.0.20210914 - https://git.zx2c4.com/wireguard-tools/

PS: The wgui logs don't say anything particular, at all.
```
Wireguard UI
App Version : development
Git Commit : N/A
Git Ref : N/A
Build Time : 01-15-2023 18:46:58
Git Repo : https://github.com/ngoduykhanh/wireguard-ui
Authentication : true
Bind address : 0.0.0.0:5000
Email from : no-reply@[REDACTED]
Email from name : vpn
Custom wg.conf :
Base path : /
⇨ http server started on [::]:5000
{"time":"2023-01-15T18:47:28.131289268Z","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:5000","method":"GET","uri":"/_health","user_agent":"Wget","status":200,"error":"","latency":4990,"latency_human":"4.99µs","bytes_in":0,"bytes_out":2}
{"time":"2023-01-15T18:47:58.184724738Z","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:5000","method":"GET","uri":"/_health","user_agent":"Wget","status":200,"error":"","latency":26833,"latency_human":"26.833µs","bytes_in":0,"bytes_out":2}
{"time":"2023-01-15T18:48:28.257660392Z","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:5000","method":"GET","uri":"/_health","user_agent":"Wget","status":200,"error":"","latency":54764,"latency_human":"54.764µs","bytes_in":0,"bytes_out":2}
{"time":"2023-01-15T18:48:58.327378353Z","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:5000","method":"GET","uri":"/_health","user_agent":"Wget","status":200,"error":"","latency":26350,"latency_human":"26.35µs","bytes_in":0,"bytes_out":2}
{"time":"2023-01-15T18:49:28.401595279Z","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:5000","method":"GET","uri":"/_health","user_agent":"Wget","status":200,"error":"","latency":25661,"latency_human":"25.661µs","bytes_in":0,"bytes_out":2}
{"time":"2023-01-15T18:49:58.461058959Z","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:5000","method":"GET","uri":"/_health","user_agent":"Wget","status":200,"error":"","latency":29346,"latency_human":"29.346µs","bytes_in":0,"bytes_out":2}
{"time":"2023-01-15T18:50:28.549025544Z","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:5000","method":"GET","uri":"/_health","user_agent":"Wget","status":200,"error":"","latency":37923,"latency_human":"37.923µs","bytes_in":0,"bytes_out":2}
{"time":"2023-01-15T18:50:58.622828458Z","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:5000","method":"GET","uri":"/_health","user_agent":"Wget","status":200,"error":"","latency":25770,"latency_human":"25.77µs","bytes_in":0,"bytes_out":2}
{"time":"2023-01-15T18:51:28.686035737Z","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:5000","method":"GET","uri":"/_health","user_agent":"Wget","status":200,"error":"","latency":30328,"latency_human":"30.328µs","bytes_in":0,"bytes_out":2}
```
