### ISSUE TITLE
Route traffic to local network

### ISSUE THREAD

**Issue by davidclaeysquinones** [ngoduykhanh/wireguard-ui#321]
I've been trying to get this setup as a docker container.
This is the docker compose file I've been using

```
version: "3"
services:
  wg-ui:
    image: ngoduykhanh/wireguard-ui
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WGUI_USERNAME=${WGUI_USERNAME}
      - WGUI_PASSWORD=${WGUI_PASSWORD}
      - WGUI_SERVER_LISTEN_PORT=${WGUI_SERVER_LISTEN_PORT}
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
      #- WGUI_SERVER_POST_UP_SCRIPT=DROUTE=$(ip route | grep default | awk '{print $3}'); HOMENET=192.168.0.0/16; HOMENET2=10.0.0.0/8; HOMENET3=172.16.0.0/12; ip route add $HOMENET3 via $DROUTE;ip route add $HOMENET2 via $DROUTE; ip route add $HOMENET via $DROUTE;iptables -I OUTPUT -d $HOMENET -j ACCEPT;iptables -A OUTPUT -d $HOMENET2 -j ACCEPT; iptables -A OUTPUT -d $HOMENET3 -j ACCEPT;  iptables -A OUTPUT ! -o %i -m mark ! --mark $(wg show wg0 fwmark) -m addrtype ! --dst-type LOCAL -j REJECT
      #- WGUI_SERVER_POST_DOWN_SCRIPT=HOMENET=192.168.0.0/16; HOMENET2=10.0.0.0/8; HOMENET3=172.16.0.0/12; ip route del $HOMENET3 via $DROUTE;ip route del $HOMENET2 via $DROUTE; ip route del $HOMENET via $DROUTE; iptables -D OUTPUT ! -o %i -m mark ! --mark $(wg show wg0 fwmark) -m addrtype ! --dst-type LOCAL -j REJECT; iptables -D OUTPUT -d $HOMENET -j ACCEPT; iptables -D OUTPUT -d $HOMENET2 -j ACCEPT; iptables -D OUTPUT -d $HOMENET3 -j ACCEPT
      - TZ=${TIME_ZONE}
    volumes:
      - ${WGUI_CONFIG_FOLDER}:/app/db
      - ${WG_CONFIG_FOLDER}:/etc/wireguard
    #sysctls:
      #- net.ipv4.conf.all.src_valid_mark=1
    network_mode: host
    #ports:
    #  - 5000:5000
    #  - ${WGUI_SERVER_LISTEN_PORT}:${WGUI_SERVER_LISTEN_PORT}
```
There are a couple of things that bother me, first of all that I need to use the host network for the image. Although this is something I can live with.

You can see that I've some lines commented out, because I wanted to show what I've been trying.
The most important of them is makings some scripts that allow me to route traffic through my local network.

Since I'm not very familiar with iptables and routing commands in general I've tried using the example from [linuxserver/wireguard](https://hub.docker.com/r/linuxserver/wireguard). However the provided example does not work in this container.
All I would like is since this is (at least in my opinion) a very common use case, it would be nice if an example script could be provided in the documentation to route wireguard traffic trough the local network.

**Comment by systemcrash** [comment]
When you get the example script working, let us know, then it can be provided. 

What flavour linux does linuxserver.io provide? What flavour linux does this image provide? Subtle differences may account for why it is not working. So work through every single command both on your docker host (host mode), and in your docker image, to find where the dependency chain breaks down. You might also learn something in the process. Ask yourself, who is not familiar with routing commands in general, whether you really need to route all three RFC1918 subnet classes via the default gateway. If not, simplify the commands. 

Check whether double `=` are problematic. e.g. `WGUI_SERVER_POST_UP_SCRIPT=DROUTE=...`

I run host mode, but not networks, only an interface.

**Comment by davidclaeysquinones** [comment]
linuxserver.io runs on top of alpine. I've tried to get the command to work but to be honest I have not been able to get it to work.
I definitively will post the commands if I find out.

**Comment by davidclaeysquinones** [comment]
Part of the example that causes the issues is :
`iptables -A OUTPUT ! -o %i -m mark ! --mark $(wg show %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT`

I guess that the iptables command should return some kind of array but for some reason this command sequence is not valid.

**Comment by davidclaeysquinones** [comment]
I have done another set of attempts:

```
ip route add 192.168.0.0/24 via 192.168.0.1;iptables -A OUTPUT -d 192.168.0.0/24 -j ACCEPT;
ip route add 192.168.0.0/24 via 192.168.0.1;iptables -I INPUT -i wg0 -j ACCEPT;iptables -A OUTPUT -d 192.168.0.0/24 -j ACCEPT;

iptables -t mangle -A PREROUTING -i wg0 -j MARK --set-mark 0xca6c;iptables -t nat -A POSTROUTING ! -o wg0 -m mark --mark 0xca6c -j MASQUERADE;
iptables -t mangle -D PREROUTING -i wg0 -j MARK --set-mark 0xca6c;iptables -t nat -D POSTROUTING ! -o wg0 -m mark --mark 0xca6c -j MASQUERADE;
```

These commands are much simpler but yet it doesn't work as intended. I'm afraid I'm far out my dept.
I have the suspicion that the reason it doesn't work is because we are talking about different subnets. With the first option I've got outbound traffic working and local traffic to. It's still impossible to reach other clients on the same subnet.
Which I expected at this point. Hopefully someone more knowledgeable can point out what's going on, since it's probably obvious to someone with some more understanding.

**Comment by davidclaeysquinones** [comment]
In addition to that, I found out (the hard way) that while editing the settings of the container I actually was changing my docker host settings. Taking into account that in order to work correctly this container has to be exposed in one or another way to the outside world, I would strongly suggest to not use the suggested setup (network host mode).
Instead you can just map the ports you'll need in docker and reduce the attack surface.  

With this docker compose file you can do what I just suggested :

```
version: "3"
services:
  wg-ui:
    image: ngoduykhanh/wireguard-ui
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WGUI_USERNAME=${WGUI_USERNAME}
      - WGUI_PASSWORD=${WGUI_PASSWORD}
      - WGUI_SERVER_LISTEN_PORT=${WGUI_SERVER_LISTEN_PORT}
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
      - TZ=${TIME_ZONE}
    volumes:
      - ${WGUI_CONFIG_FOLDER}:/app/db
      - ${WG_CONFIG_FOLDER}:/etc/wireguard

    ports:
      - 5000:5000
      - ${WGUI_SERVER_LISTEN_PORT}:${WGUI_SERVER_LISTEN_PORT}/udp
    sysctls:
       - net.ipv4.conf.all.src_valid_mark=1
      
```
