### ISSUE TITLE
Feature: Linuxserver wireguard docker compose

### ISSUE THREAD

**Issue by sgiannulli** [ngoduykhanh/wireguard-ui#338]
Hello,
just spending time trying to make a compose file that works with linuxserver wireguard without luck. Sometimes wireguard android app does not connect sometimes it does but no way to connect to a couple of servers on my local network. I have tried all config examples in issues and no one is working. It would be great to have an official docker compose example explaining also if some post up and down needs to be entered.
Thank you

**Comment by ngoduykhanh** [comment]
Please check the example that was contributed recently.

**Comment by poulou0** [comment]
Thank you so very much that you are providing with such a useful tool!! 
I've been struggling to set everything up in docker for a couple of hours.

I used the `linuxserver.yml` example as my starting point. 
Don't we need to set the "**PEERS**" env variable to run in server mode?
> ### Server Mode
> If the environment variable PEERS is set to a number or a list of strings separated by comma, the container will run in server mode and the necessary server and peer/client confs will be generated

By setting the PEERS=1 in the `wireguard` container everything works perfectly... for the first time!

(In the logs there is still an error `s6-rc: warning: unable to start service svc-wireguard: command exited 1`..
_Maybe related to `WGUI_MANAGE_START`?_)

Any time i restart the containers nothing works anymore

Reproducable example:
```yaml
version: "3"

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - PEERS=1
    volumes:
      - ./config:/config
    ports:
      - 51820:51820/udp
      - 8015:5000
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET
      - WGUI_USERNAME=admin
      - WGUI_PASSWORD=${PASSWORD}
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - ./config:/etc/wireguard
```
Any help is appreciated!!
