### ISSUE TITLE
Docker compose deployment failed

### ISSUE THREAD

**Issue by threerog** [ngoduykhanh/wireguard-ui#353]
```
[#] ip link add wg0 type wireguard
Error: Unknown device type.
Unable to access interface: Protocol not supported
[#] ip link delete dev wg0
Cannot find device "wg0"
Wireguard UI
App Version	: development
Git Commit	: 
Git Ref		: N/A
Build Time	: 04-02-2023 01:14:44
Git Repo	: https://github.com/ngoduykhanh/wireguard-ui
Authentication	: true
Bind address	: 0.0.0.0:5000
Email from	: 
Email from name	: WireGuard UI
Custom wg.conf	: 
Base path	: /
⇨ http server started on [::]:5000
```

```
wg-quick: `wg0' is not a WireGuard interface
[#] ip link add wg0 type wireguard
Error: Unknown device type.
Unable to access interface: Protocol not supported
[#] ip link delete dev wg0
Cannot find device "wg0"
Wireguard UI
App Version	: development
Git Commit	: 
Git Ref		: N/A
Build Time	: 04-02-2023 01:16:49
Git Repo	: https://github.com/ngoduykhanh/wireguard-ui
Authentication	: true
Bind address	: 0.0.0.0:5000
Email from	: 
Email from name	: WireGuard UI
Custom wg.conf	: 
Base path	: /
⇨ http server started on [::]:5000
```

```
version: "3"

services:
  wg:
    build: .
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wgui
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    network_mode: host
    environment:
      - WGUI_USERNAME=admin
      - WGUI_PASSWORD=admin
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - /etc/wireguard:/etc/wireguard
```

The webui is normal but the wg client cannot connect
My firewall is fully open
