### ISSUE TITLE
Unable to access web ui with host networking enabled

### ISSUE THREAD

**Issue by Umbergrove** [ngoduykhanh/wireguard-ui#357]
Been trying to figure out how to access the wg-ui on port 5000 with `network_mode: host` to no avail. I can't find any obvious errors in my setup other than the timed out connection error when trying to access the ui. I can in fact access the web ui when using bridge networking and specifying `ports: 5000:5000` but, as documented before, the container is unable to detect connected clients.

Here's my docker compose referencing the [system default compose configuration](https://github.com/ngoduykhanh/wireguard-ui/blob/master/examples/docker-compose/system.yml)
```
version: "3"

services:
  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    cap_add:
      - NET_ADMIN
    # required to show active clients. with this set, you don't need to expose the ui port (5000) anymore
    network_mode: host
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET

      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - /etc/wireguard:/etc/wireguard
```

Here's the output of `sudo ss -tulpn | grep LISTEN` on the host machine running docker:
```
tcp   LISTEN 0      4096         0.0.0.0:443        0.0.0.0:*    users:(("docker-proxy",pid=151948,fd=4))
tcp   LISTEN 0      4096         0.0.0.0:8000       0.0.0.0:*    users:(("docker-proxy",pid=1248,fd=4))  
tcp   LISTEN 0      4096         0.0.0.0:9443       0.0.0.0:*    users:(("docker-proxy",pid=1176,fd=4))  
tcp   LISTEN 0      4096         0.0.0.0:80         0.0.0.0:*    users:(("docker-proxy",pid=151988,fd=4))
tcp   LISTEN 0      4096         0.0.0.0:8080       0.0.0.0:*    users:(("docker-proxy",pid=129495,fd=4))
tcp   LISTEN 0      4096         0.0.0.0:81         0.0.0.0:*    users:(("docker-proxy",pid=151967,fd=4))
tcp   LISTEN 0      4096         0.0.0.0:53         0.0.0.0:*    users:(("docker-proxy",pid=129515,fd=4))
tcp   LISTEN 0      128          0.0.0.0:22         0.0.0.0:*    users:(("sshd",pid=1822,fd=3))          
tcp   LISTEN 0      100          0.0.0.0:25         0.0.0.0:*    users:(("master",pid=1434,fd=13))       
tcp   LISTEN 0      4096            [::]:443           [::]:*    users:(("docker-proxy",pid=151953,fd=4))
tcp   LISTEN 0      4096            [::]:8000          [::]:*    users:(("docker-proxy",pid=1254,fd=4))  
tcp   LISTEN 0      4096            [::]:9443          [::]:*    users:(("docker-proxy",pid=1194,fd=4))  
tcp   LISTEN 0      4096               *:5000             *:*    users:(("wg-ui",pid=319977,fd=6))       
tcp   LISTEN 0      4096            [::]:80            [::]:*    users:(("docker-proxy",pid=151993,fd=4))
tcp   LISTEN 0      4096            [::]:8080          [::]:*    users:(("docker-proxy",pid=129501,fd=4))
tcp   LISTEN 0      4096            [::]:81            [::]:*    users:(("docker-proxy",pid=151972,fd=4))
tcp   LISTEN 0      4096            [::]:53            [::]:*    users:(("docker-proxy",pid=129521,fd=4))
tcp   LISTEN 0      128             [::]:22            [::]:*    users:(("sshd",pid=1822,fd=4))          
tcp   LISTEN 0      100             [::]:25            [::]:*    users:(("master",pid=1434,fd=14))
```

And the log of the container obtained from portainer's ui:
```
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.252.1.0/24 dev wg0
[#] ip link set mtu 1450 up dev wg0
[#] 
Wireguard UI
App Version	: development
Git Commit	: 
Git Ref		: N/A
Build Time	: 04-10-2023 20:22:55
Git Repo	: https://github.com/ngoduykhanh/wireguard-ui
Authentication	: true
Bind address	: 0.0.0.0:5000
Email from	: 
Email from name	: WireGuard UI
Custom wg.conf	: 
Base path	: /
⇨ http server started on [::]:5000
```

Sorry if this issue if fairly simple, I'm a novice docker user
