### ISSUE TITLE
Docker Compose secrets not passing into env vars

### ISSUE THREAD

**Issue by cameronawichman** [ngoduykhanh/wireguard-ui#389]
After toiling with my secret files in docker compose, I realized that the contents of the secret files aren't being passed into environment variables such as WGUI_PASSWORD and SMTP_PASSWORD. Is my compose file set up correctly or is this feature not supported as of yet?

```
version: "3"

volumes:
  wireguard-ui_db:
    external: true

services:
  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    cap_add:
      - NET_ADMIN
    # required to show active clients. with this set, you don't need to expose the ui port (5000) anymore
    network_mode: host
    #ports:
    #  - ${CUSTOM_PORT}:5000
    environment:
      - SESSION_SECRET=/run/secrets/session-secret
      - WGUI_USERNAME=JohnDoe
      - WGUI_PASSWORD=/run/secrets/password

      - WGUI_ENDPOINT_ADDRESS=interesting.domain.com
      - WGUI_DNS=192.168.2.1
      #- WGUI_MTU=1450
      - WGUI_PERSISTENT_KEEPALIVE=25
      - WGUI_FIREWALL_MARK=0xca6c
      
      - WGUI_LOG_LEVEL=INFO

      - EMAIL_FROM_ADDRESS=JohnDoe@gmail.com
      - EMAIL_FROM_NAME=Wireguard UI
      - SMTP_HOSTNAME=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=JohnDoe@gmail.com
      - SMTP_PASSWORD=/run/secrets/smtp-password
      - SMTP_AUTH_TYPE=LOGIN
      - SMTP_ENCRYPTION=STARTTLS
      
      - WGUI_SERVER_INTERFACE_ADDRESSES=10.0.0.0/24
      - WGUI_SERVER_LISTEN_PORT=51820
      - WGUI_SERVER_POST_UP_SCRIPT=ufw route allow in on wg0 out on ens1; iptables -t nat -I POSTROUTING -o ens1 -j MASQUERADE; ip6tables -t nat -I POSTROUTING -o ens1 -j MASQUERADE
      - WGUI_SERVER_POST_DOWN_SCRIPT=ufw route delete allow in on wg0 out on ens1; iptables -t nat -D POSTROUTING -o ens1 -j MASQUERADE; ip6tables -t nat -D POSTROUTING -o ens1 -j MASQUERADE

      - WGUI_DEFAULT_CLIENT_ALLOWED_IPS=0.0.0.0/0
      - WGUI_DEFAULT_CLIENT_USE_SERVER_DNS=true
      - WGUI_DEFAULT_CLIENT_ENABLE_AFTER_CREATION=true

      - WGUI_MANAGE_START=false
      - WGUI_MANAGE_RESTART=false
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - wireguard-ui_db:/app/db
      - /etc/wireguard:/etc/wireguard
    secrets:
      - session-secret
      - smtp-password
    restart: unless-stopped

secrets:
    session-secret:
        file: /root/.secrets/wireguard-ui/session-secret
    smtp-password:
        file: /root/.secrets/wireguard-ui/smtp-password
```
