### ISSUE TITLE
using linuxiac guid: server only starts on ipv6 

### ISSUE THREAD

**Issue by hanscees** [ngoduykhanh/wireguard-ui#406]
Hi,

I am using this guide:
https://linuxiac.com/how-to-set-up-wireguard-vpn-with-docker/#comment-39633

At first the server gui on port 5000 works fine.
After the first client is configured it stops working.
It seems the server only listens op ipv6 for some reason.

'''
wireguard-ui  | Wireguard UI
wireguard     | **** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
wireguard-ui  | App Version	: dev
wireguard-ui  | Git Commit	: 6bbe230
wireguard-ui  | Git Ref		: N/A
wireguard-ui  | Build Time	: 07-14-2023 20:30:20
wireguard-ui  | Git Repo	: https://github.com/ngoduykhanh/wireguard-ui
wireguard-ui  | Authentication	: true
wireguard-ui  | Bind address	: 0.0.0.0:5000
wireguard-ui  | Email from	: 
wireguard-ui  | Email from name	: WireGuard UI
wireguard-ui  | Custom wg.conf	: 
wireguard-ui  | Base path	: /
wireguard-ui  | ⇨ http server started on [::]:5000
'''

**Comment by hanscees** [comment]
here is my docker-compose.tml

```
version: "3"

services:

  # WireGuard VPN service
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    #restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - Wconfig:/etc/wireguard
      - Wconfig2:/config
    ports:
      # Port for WireGuard-UI
      - "5000:5000"
      # Port of the WireGuard VPN server
      - "51820:51820/udp"

  # WireGuard-UI service
  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    # Use the network of the 'wireguard' service
    # This enables to show active clients in the status page
    network_mode: service:wireguard
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET
     - WGUI_LOG_LEVEL:DEBUG
      - WGUI_USERNAME=admin
      - WGUI_PASSWORD=SecletShit98$
      - WG_CONF_TEMPLATE
      - BIND_ADDRESS=0.0.0.0:5000
      - WGUI_MANAGE_START=false
      - WGUI_MANAGE_RESTART=true
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - Wdb:/app/db
      - Wconfig:/etc/wireguard
      - Wconfig2:/config

volumes:
   Wconfig:
   Wconfig2:
   Wdb:
```
