### ISSUE TITLE
HTTPS/SSL Support in Docker Container mode

### ISSUE THREAD

**Issue by magyarlatin** [ngoduykhanh/wireguard-ui#421]
Hi there!

Is there a way to use a certificate and enable HTTPS/SSL support using the Docker container image?

Thank you in advance.

**Comment by DiegoSpinola** [comment]
I'm using caddy in a docker-compose stack to add this to my setup

here's an example:

```
version: "3"

services:
  wg:
    build: .
    #image: ngoduykhanh/wireguard-ui:latest
    container_name: wgui
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET
      - WGUI_USERNAME=alpha
      - WGUI_PASSWORD=this-unusual-password
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=false
      - WGUI_MANAGE_RESTART=false
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - /etc/wireguard:/etc/wireguard

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wg

volumes:
  caddy_data: {}
```


caddy file should look like this:

```
yourdomain.com {
    reverse_proxy wg:8080
    tls {
        email youremail@domain.com
    }
}
```

caddy will handle certificate renewal and all that automagically

**Comment by thumpco** [comment]
@DiegoSpinola - does the WGUI "Status" page work correctly in your reverse proxy setup above?  I've tried several reverse proxy setups and keep running into this issue: https://github.com/ngoduykhanh/wireguard-ui/issues/429

**Comment by thumpco** [comment]
@DiegoSpinola - just tried your exact config.. unfortunately seems to have the same issue (for me at least).

**Comment by ThomFri** [comment]
I am using an nginx reverse proxy quite similar to issue https://github.com/ngoduykhanh/wireguard-ui/issues/421. Status page works just fine in my setup.

**Comment by thumpco** [comment]
> I am using an nginx reverse proxy quite similar to issue #421. Status page works just fine in my setup.

Yes.. I posted my solution on another thread.  When I setup the reverse proxy I removed "host" networking from the WGUI docker container so the proxy would just access it internally through docker networking.  This had the impact of WGUI not being able to collect Status page stats form the wg0 interface.   Once host networking was added back, it all works as expected.

**Comment by ThomFri** [comment]
Ah, sorry I didn't see that at https://github.com/ngoduykhanh/wireguard-ui/issues/429 ! Nevertheless, I had actually linked the wrong issue above, I wanted to refer to the nginx configuration from issue https://github.com/ngoduykhanh/wireguard-ui/issues/439. But yes, I agree with you, the clue is simply setting "network: host" [or in general to assure the (network) access of the UI to the wireguard status, also e.g. for the case that wireguard itself runs on Docker]

**Comment by kungfoome** [comment]
Here is a full example in case anyone wants to get this setup. Status still works and it will bring up and down the wg0 interface. This also binds it to the ip, so that port 5000 isn't open to the public, only 443.

Few things to note. The caddy in this example is in the same directory as my docker-compose file. You can move that where you like, just make sure to point to the correct caddyfile. I had to bind the address to the wireguard ip. Then in the caddy file, point to the same ip. After this, the only port you should see open is 0.0.0.0:443 and then the internal one 10.0.0.0:5000.

You could also try to run caddy network_mode as host as well. Then you can bind to the 127.0.0.1 address instead. In theory that should work, but I did not try.

docker-compose.yaml
```yaml
services:
  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - BIND_ADDRESS=10.0.0.0:5000
    restart: unless-stopped

  caddy:
    image: caddy
    restart: unless-stopped
    container_name: caddy
    ports:
      - "443:443"
    volumes:
      - $PWD/caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - wireguard-ui

volumes:
  caddy_data: {}

```

caddyfile
```yaml
your.domain.com {
  reverse_proxy 10.0.0.0:5000
}
```
