### ISSUE TITLE
No internet connection using docker

### ISSUE THREAD

**Issue by MarvinJWendt** [ngoduykhanh/wireguard-ui#449]
Hi, I use the docker compose setup.

Using the default template, my clients don't have access to the internet, even tho they are connected.

I fixed it by appending the following to the `Interface` configuration:

```yml
PreUp = iptables --table nat --append POSTROUTING --jump MASQUERADE --out-interface eth0
PreDown = iptables --table nat --delete POSTROUTING --jump MASQUERADE --out-interface eth0
```

To make the configuration persistent, I use a custom tempalte:

```
# This file was generated using wireguard-ui (https://github.com/ngoduykhanh/wireguard-ui)
# Please don't modify it manually, otherwise your change might get replaced.

# Address updated at:     {{ .serverConfig.Interface.UpdatedAt }}
# Private Key updated at: {{ .serverConfig.KeyPair.UpdatedAt }}
[Interface]
Address = {{$first :=true}}{{range .serverConfig.Interface.Addresses }}{{if $first}}{{$first = false}}{{else}},{{end}}{{.}}{{end}}
ListenPort = {{ .serverConfig.Interface.ListenPort }}
PrivateKey = {{ .serverConfig.KeyPair.PrivateKey }}
{{if .globalSettings.MTU}}MTU = {{ .globalSettings.MTU }}{{end}}
PreUp = iptables --table nat --append POSTROUTING --jump MASQUERADE --out-interface eth0
PreDown = iptables --table nat --delete POSTROUTING --jump MASQUERADE --out-interface eth0
PostUp = {{ .serverConfig.Interface.PostUp }}
PostDown = {{ .serverConfig.Interface.PostDown }}
Table = {{ .globalSettings.Table }}

{{range .clientDataList}}{{if eq .Client.Enabled true}}
# ID:           {{ .Client.ID }}
# Name:         {{ .Client.Name }}
# Email:        {{ .Client.Email }}
# Created at:   {{ .Client.CreatedAt }}
# Update at:    {{ .Client.UpdatedAt }}
[Peer]
PublicKey = {{ .Client.PublicKey }}
{{if .Client.PresharedKey }}PresharedKey = {{ .Client.PresharedKey }}
{{end}}AllowedIPs = {{$first :=true}}{{range .Client.AllocatedIPs }}{{if $first}}{{$first = false}}{{else}},{{end}}{{.}}{{end}}{{range .Client.ExtraAllowedIPs }},{{.}}{{end}}
{{end}}{{end}}
```

This fixed my docker compose setup.
Maybe something like this should be included in the default template.

**Comment by ethaniel86** [comment]
can confirm this solution works for docker compose method. Thanks! :D

**Comment by domi-btnr** [comment]
I'm having the same Problem, but I'm not able to fix it. I'm using the [`linuxserver.yml`](https://github.com/ngoduykhanh/wireguard-ui/blob/master/examples/docker-compose/linuxserver.yml) and tried to change it in the following files:
- `/etc/wireguard/wg0.conf`
- `/etc/wireguard/templates/peer.conf`
- `/etc/wireguard/templates/server.conf`

Also updated the `docker-compose.yml` to use the respective files as template but without success.
<details>
<summary>Changing it in the Server Panel also doesn't change anything. </summary>
<img width="603" alt="Screenshot 2023-10-22 at 18 23 07" src="https://github.com/ngoduykhanh/wireguard-ui/assets/50876016/032af4f4-df0e-4d70-b5aa-5293fb694af5">
</details>

I slightly changed my docker-compose file to add it to my Reverse Proxy Network, but I don't think that's the Issue.
<details>
<summary>That's my modified <code>docker-compose.yml</code></summary>

```yml
version: "3"

services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/wireguard:/config
    ports:
      # port for wireguard-ui. this must be set here as the `wireguard-ui` container joins the network of this container and hasn't its own network over which it could publish the ports
      - "5000:5000"
      # port of the wireguard server
      - "51820:51820/udp"
    networks:
      - nginx-proxy-manager_default

  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    # use the network of the 'wireguard' service. this enables to show active clients in the status page
    network_mode: service:wireguard
    environment:
      - WGUI_USERNAME=admin
      - WGUI_PASSWORD=admin
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - /etc/wireguard/ui:/app/db
      - /etc/wireguard:/etc/wireguard

networks:
  nginx-proxy-manager_default:
    external: true
```

</details>
