### ISSUE TITLE
Wireguard confs moved to /config/wg_confs/

### ISSUE THREAD

**Issue by Dirk--** [ngoduykhanh/wireguard-ui#456]
https://newreleases.io/project/github/linuxserver/docker-wireguard/release/v1.0.20210914-ls8

**Comment by tom666-debug** [comment]
I also noticed this change already. So for me wireguard-ui stopped working after updating to the latest wireguard (docker) release.
A simple adjustment of the path variables within docker-compose.yml didnt work. So, whats the trick to get it working again? Do I need to patch the database as well?

**Comment by capdeveloping** [comment]
workaround for me is doing a softlink inside the container. "/etc/wireguard/wg0.conf -> /config/wg0.conf". And  /config/wg_confs/wg0.conf -> /config/wg0.conf

**Comment by tom666-debug** [comment]
@capdeveloping thx for your feedback. I will give it a try.

**Comment by Mindless999** [comment]
For me what I did to get it running (for now) is to delete the '/config/wg0.conf' since that one was empty, and '/config/wg_confs/wg0.conf' had all the information and since then it did work. Every time starting the docker it will re-create the '/config/wg0.conf' and I need to use sudo / root to delete this.

**Comment by Mindless999** [comment]
Just a bit of an update. Note this is a WORKAROUND; this will not start the docker at boot, unless you specifically delete the file before starting the docker!

I changed my docker compose file to the following. I run the docker on its own user, so make sure you change the userid to what you're using:
```
version: "3"

services:

  # WireGuard VPN service
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    environment:
      - PUID=1001
      - PGID=1001
      - PEERS=1
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/config
    restart: always
    ports:
      # Port for WireGuard-UI
      - "5000:5000"
      # Port of the WireGuard VPN server
      - "51820:51820/udp"

  # WireGuard-UI service
  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    # Use the network of the 'wireguard' service
    # This enables to show active clients in the status page
    network_mode: service:wireguard
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET
      - WGUI_USERNAME=<SUPERSECRETUSER>
      - WGUI_PASSWORD=<SUPERSECRETPASSWORD>
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
      - PUID=1001
      - PGID=1001
      - PEERS=1
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - ./config:/etc/wireguard
```

Afer this, to also update the docker which will remove the file on every step (just in case) when updating, for that I use the following scrip called update.sh
```
#/bin/bash
rm -f ~/config/wg0.conf
docker compose pull
docker compose down
rm -f ~/config/wg0.conf
docker compose up -d
rm -f ~/config/wg0.conf
```

**Comment by Mindless999** [comment]
Is there any update on this? I currently need to delete the file and re-apply the configuration after every reboot for some reason, I would've assumed it would be fixed, but it doesn't seem to be fixed (unless I missed something with the changes and need a configuration change)

**Comment by avoidik** [comment]
```yaml
services:
  wireguard-ui:
    environment:
      - WGUI_CONFIG_FILE_PATH=/etc/wireguard/wg_confs/wg0.conf
```
