### ISSUE TITLE
Fail to install on fresh docker of digitalocean server

### ISSUE THREAD

**Issue by alexlii1971** [ngoduykhanh/wireguard-ui#47]
Hello,

I found wirreguard-ui by 

`docker search wireguard`

I tried installation on fresh docker, but no luck to me.

I just suppose I missed some steps, so is there an full tutorial for newbies please?

Thanks

**Comment by alexlii1971** [comment]
It will alway loop as following:

wgui  | {"time":"2021-01-13T08:57:28.702214357Z","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:5000","method":"GET","uri":"/login","user_agent":"Wget","status":200,"error":"","latency":126515,"latency_human":"126.515µs","bytes_in":0,"bytes_out":4877}

what did I miss or any issue here please?

**Comment by DalekFrog** [comment]
> 
> 
> It will alway loop as following:
> 
> wgui | {"time":"2021-01-13T08:57:28.702214357Z","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:5000","method":"GET","uri":"/login","user_agent":"Wget","status":200,"error":"","latency":126515,"latency_human":"126.515µs","bytes_in":0,"bytes_out":4877}
> 
> what did I miss or any issue here please?

you did not miss anything .
the output is just wgui's access log . requests are from docker's healthcheck .

if you can't open port 5000 ,make sure the port has  exposed by `docker -p`

**Comment by nathandtrone** [comment]
I've just started up an instance of this docker using the following docker-compose and it appears to be failing. It's running, and made it past the healthcheck.

```
version: '3'
services:
  wg:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard_ui
    ports:
      - 4080:5000
      - 51820:51820
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - /home/docker/wireguard/db:/app/db
      - /home/docker/wireguard/config:/etc/wireguard
```

Here are the interfaces from within the VM:
```
eth0      Link encap:Ethernet  HWaddr 01:23:45:67:90:12  
          inet addr:199.199.0.2  Bcast:199.199.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:7550 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2232 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:10589482 (10.0 MiB)  TX bytes:986950 (963.8 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:9110 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9110 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:4347370 (4.1 MiB)  TX bytes:4347370 (4.1 MiB)
```

I've run `sudo docker port abcde7654321` with the result:
```
5000/tcp -> 0.0.0.0:4080
51820/tcp -> 0.0.0.0:51820
```
So things are.. there..
I'm not sure what I'm missing on this. I'm able to use the web interface, change configurations. I also connected my phone to this thing, and the client doesn't complain, but I have no network access.
