### ISSUE TITLE
linuxserver wireguard

### ISSUE THREAD

**Issue by Kawabountou** [ngoduykhanh/wireguard-ui#55]
hello.

I have wireguard with linuxserverio
I would like to connect ngoduykhanh/wireguard-ui with linuxserver/wireguard
but my config is wrong. when i had a user, nothing happen.

I write my docker-compose at the end of my post.

Thank you in advance for your reply.

  ---
    version: "2.1"
    services:
      wireguard:
        image: ghcr.io/linuxserver/wireguard
        container_name: wireguard
        cap_add:
          - NET_ADMIN
          - SYS_MODULE
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/Paris
          - SERVERURL=XXXXXXXXXXXX #optional
          - SERVERPORT=51820 #optional
          - PEERS=5 #optional
          - PEERDNS=auto #optional
          - INTERNAL_SUBNET=10.13.13.0 #optional
          - ALLOWEDIPS=0.0.0.0/0 #optional
        volumes:
          - ./config:/config
          - ./modules:/lib/modules
        ports:
          - 51820:51820/udp
        sysctls:
          - net.ipv4.conf.all.src_valid_mark=1
        restart: unless-stopped
  
      wireguard-ui:
        image: ngoduykhanh/wireguard-ui
        container_name: wireguard-ui
        ports:
          - 5000:5000
        logging:
          driver: json-file
          options:
            max-size: 50m
        volumes:
          - ./db:/app/db
          - /wireguard:/etc/wireguard
        links:
          - wireguard:wireguard

**Comment by weckie** [comment]
hi,

you have to point - /wireguard:/etc/wireguard to the wg0.conf file from wireguard. 
I think in you're case it is - ./config:/etc/wireguard.

kind regards

**Comment by kking124** [comment]
Did you ever get this working? I was not able to. I did notice that the PUID and PGID in wireguard-ui are different than in the linuxserver wireguard container. I changed them and the permissions seem to line up but the client list doesn't change in wg0.conf.

original permissions:
```
/app # ls -lac /etc/wireguard
total 32
drwxr-xr-x    6 1000     1000          4096 May 31 23:44 .
drwxr-xr-x    1 root     root          4096 May 31 23:44 ..
-rw-------    1 1000     1000           156 May 31 23:44 .donoteditthisfile
drwxr-xr-x    2 1000     1000          4096 May 31 23:44 coredns
drwx------    2 1000     1000          4096 May 31 23:44 peer1
drwxr-xr-x    2 1000     1000          4096 May 31 23:44 server
drwxr-xr-x    2 1000     1000          4096 May 31 23:44 templates
-rw-------    1 1000     1000           485 May 31 23:44 wg0.conf
```

permissions with changed PUID/PGID:
```
/app # ls -lac /etc/wireguard
total 32
drwxr-xr-x    6 wgui     wgui          4096 May 31 23:30 .
drwxr-xr-x    1 root     root          4096 May 31 23:30 ..
-rw-------    1 wgui     wgui           156 May 31 23:30 .donoteditthisfile
drwxr-xr-x    2 wgui     wgui          4096 May 31 23:30 coredns
drwx------    2 wgui     wgui          4096 May 31 23:30 peer1
drwxr-xr-x    2 wgui     wgui          4096 May 31 23:30 server
drwxr-xr-x    2 wgui     wgui          4096 May 31 23:30 templates
-rw-------    1 wgui     wgui           485 May 31 23:30 wg0.conf
```

docker-compose.yaml
```yaml
version: "2.1"
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=100
      - PGID=101
      - TZ=America/New_York
      - PEERS=1
    volumes:
      - wg-conf:/config
      - wg-modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always

  wgui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    ports:
      - 5000:5000
    volumes:
      - wgui-db:/app/db
      - wg-conf:/etc/wireguard
    depends_on:
      - "wireguard"
    restart: always

volumes:
  wg-conf:
    external: false
  wg-modules:
    external: false
  wgui-db:
    external: false

```

web ui:
![image](https://user-images.githubusercontent.com/21278391/120249165-f8f1e100-c247-11eb-8fa5-623dfb17b62c.png)

wg output from wireguard container after adding a user

```
root@6f274d01e75c:/# wg
interface: wg0
  public key: XXXXX
  private key: (hidden)
  listening port: 51820

peer: XXXXX
  allowed ips: 10.13.13.2/32

```

**Comment by kking124** [comment]
You need to do 2 things to make wireguard see the changes:

1. Apply the changes to the config file
2. restart the wireguard container

To apply the changes, hit the button in the top right:
![image](https://user-images.githubusercontent.com/21278391/120269840-92d08280-c276-11eb-8f6a-2b491ee43ac3.png)

You can either restart the container manually `docker restart <container>` or add another container to your docker compose to monitor the server's `wg0.conf` and auto-restart the container. You'd have to expose your container management API to that monitoring container for that to work.

before:
```
wireguard@wireguard:~/wg$ sudo docker exec -it wireguard cat /config/wg0.conf
[Interface]
Address = 10.13.13.1
ListenPort = 51820
PrivateKey = XXXXX
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
# peer1
PublicKey = XXXXX
AllowedIPs = 10.13.13.2/32
```

after:
```
[Interface]
Address = 10.13.13.1/32
ListenPort = 51820
PrivateKey = YYYYY
MTU = 1450
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE


# ID:           c2qrful24nqq2s4q5ddg
# Name:         test
# Email:        test@example.com
# Created at:   2021-06-01 04:30:50.940846174 +0000 UTC
# Update at:    2021-06-01 04:30:50.940846174 +0000 UTC
[Peer]
PublicKey = XXXXX
PresharedKey = XXXXX
AllowedIPs = 10.13.13.2/32
```

**Note: this does not update your wg0.conf, it completely replaces it. Your private key and all the peers generated from linuxserver/wireguard will be lost**

FWIW, here's my updated docker-compose.yaml, but I don't think the permissions changes were the issue.

```yaml
version: "2.1"
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - PEERS=0
    volumes:
      - wg-conf:/config
      - wg-modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always

  wgui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    ports:
      - 5000:5000
    volumes:
      - wgui-db:/app/db
      - wg-conf:/etc/wireguard
    depends_on:
      - "wireguard"
    restart: always

volumes:
  wg-conf:
    external: false
  wg-modules:
    external: false
  wgui-db:
    external: false
```

**Comment by astronyu** [comment]
Hi, I'm trying to do the same exact thing discussed in here but so far have no luck.
I'm on Synology DSM and running linuxserver/wireguard successfully, just need the UI to work.
Unfortunately, it doesn't.

I've mapped wg0.conf file but when I save through the UI, that file wasn't even touched.


version: '3.7'


```
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1053
      - PGID=65538
      - TZ=Asia/Kuala_Lumpur
      - SERVERURL=redacted #optional
      - SERVERPORT=51820 #optional
      - PEERS=5 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.0.1.1 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - /volume1/docker/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always

  wgui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    ports:
      - 5155:5155
    volumes:
      - wgui-db:/app/db
      - wg-conf:/volume1/docker/wireguard/config
    environment:
      - SENDGRID_API_KEY=redacted
      - EMAIL_FROM_ADDRESS=redacted
      - EMAIL_FROM_NAME=redacted
      - SESSION_SECRET=redacted
      - WGUI_USERNAME=redacted
      - WGUI_PASSWORD=redacted
      - BIND_ADDRESS=0.0.0.0:5155
    depends_on:
      - "wireguard"
    restart: always

volumes:
  wg-conf:
    external: false
  wg-modules:
    external: false
  wgui-db:
    external: false
```
