### ISSUE TITLE
Why so complicated?

### ISSUE THREAD

**Issue by idc77** [ngoduykhanh/wireguard-ui#562]
Man, all I want is to create the config for my server
and a client.

Why is it all so complicated?
I can't export the server configuration, I have to apply locally.
I don't want that.

JFC.

It's 3, almost 4 am and all I want for 45 minutes now is to create a server conf and a client conf and there are no reasonable examples to be found. And this "ui" isn't helping either.

**Comment by ingvarch** [comment]
Easy as pie.

Step 1.

```
sudo apt install wireguard
```

Step 2. 

```
docker compose up -d 
```

```
services:
  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - SESSION_SECRET
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
      - WGUI_USERNAME=admin
      - WGUI_PASSWORD=admin
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - /etc/wireguard:/etc/wireguard
```

Step 3. 

Login to  `http://super_domain.com:5000` with admin/admin

Step 4. 

Add clients, download client configs and `apply` config (right top corner)

Step 5. 

```
cat /etc/wireguard/wg0.conf
```

Profit.
