### ISSUE TITLE
UI does not load config

### ISSUE THREAD

**Issue by nowaythatsok** [ngoduykhanh/wireguard-ui#663]
I installed a stack like this:
https://docs.techdox.nz/wireguard/#
I set up a few clients and all seemed ok, but after the server restarted all of the clients disappeared from the UI. 

I changed the binding of the config to my home directory: 
``` 
  wireguard:
...
    volumes:
      - /home/itsme/wireguard_setup:/config

  wireguard-ui:
...
    volumes:
      - ./db:/app/db
      - /home/itsme/wireguard_setup:/etc/wireguard
```
and I see that the clients are saved into the config file, but they do not show up in the UI. If I save a new client the config file is overwritten. Why could this be?

```
itsme@server:~/wireguard_config$ ls -lah
total 32K
drwxrwxr-x  5    911    911 4.0K Jan 13 15:10 .
drwxr-x--- 11 itsme itsme 4.0K Jan 13 14:53 ..
drwxr-xr-x  2    911    911 4.0K Jan 13 14:56 coredns
-rwxr-xr-x  1    911    911  243 Jan 13 15:02 healthcheck.sh
-rwxr-xr-x  1    911    911   19 Jan 13 15:09 healthcheck_dummy.sh
drwxr-xr-x  2    911    911 4.0K Jan 13 14:56 templates
-rw-r--r--  1    911    911  883 Jan 13 15:12 wg0.conf
drwxr-xr-x  2    911    911 4.0K Jan 13 14:56 wg_confs
```
