### ISSUE TITLE
UI wont start on Raspberry Pi Zero

### ISSUE THREAD

**Issue by PaluZoli** [ngoduykhanh/wireguard-ui#665]
Hello,
First of all thank you for your work!
I have used PiVPN which is now not working Bookworm. I have installed Wireguard, and also downloaded the wireguard-ui-v0.6.2-linux-arm.tar.gz
I'm able to unpack it no issue, but when I try to start it responds with: Illegal instruction.
I have followed the https://www.bachmann-lan.de/raspberry-pi-mit-wireguard-und-wireguard-ui-webinterface/   instructions. 
It works well in an LCX container (wireguard-ui-v0.6.2-linux-amd64.tar.gz) but not on Pi Zero (wireguard-ui-v0.6.2-linux-arm.tar.gz)

Could you help me to identify the problem? 

Meanwhile I have found out that pi zero is ARM6 based and most probably wireguard-ui should be compiled for it. 
Who can help me with that?

**Comment by samrocketman** [comment]
You need arm64; not arm download.

**Comment by raihei** [comment]
> You need arm64; not arm download.

Pi zero (not Pi zero 2 w) only supports 32-bit Raspbian, therefore arm64 is the wrong architecture. 

@PaluZoli wireguard-ui-v0.6.2-linux-arm.tar.gz should be correct (if it supports ARMv6), but I am also getting the "illegal instruction" error on a pi zero.

Looks like it was compiled for ARMv7

```
name: wireguard-ui build release

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, darwin/386, darwin/amd64
        goos: [linux, freebsd, darwin]
        goarch: [386, amd64, arm, arm64]
        exclude:
          - goarch: 386
            goos: darwin
          - goarch: arm
            goos: darwin
          - goarch: arm64
            goos: darwin
        goarm:
          - 7
```



If I compile it for ARMv6, it works also on Pi zero
