### ISSUE TITLE
--disable-login breaks healthcheck

### ISSUE THREAD

**Issue by solipsist01** [ngoduykhanh/wireguard-ui#73]
when the --disable-login command is issued, http://127.0.0.1:5000/login isn't accessible anymore

i have added the following in my compose file to override the healthcheck, which solves the problem.

```
    healthcheck:
      test: ["CMD", "wget","--output-document=-","--quiet","--tries=1","http://127.0.0.1:5000"]
      interval: 30s
      timeout: 10s
```

perhaps it's better to change the dockerfile not to check /login
