### ISSUE TITLE
docker-compose.yml - doesn't work/incorrectly documented?

### ISSUE THREAD

**Issue by total2003** [ngoduykhanh/wireguard-ui#87]
Hello everyone. I stumbled across the project and must say I like it very much.

I guess I found a few mistakes or at least for me confusing example in the file [docker-compose.yaml](https://github.com/ngoduykhanh/wireguard-ui/blob/master/docker-compose.yaml). By the way you called the file `.yaml`, but in the documentation it says `.yml.` Only as a small note.

First I tried to install the GUI in the following way. Whether this was intended, I do not know, but this is how I understood it:
````
version: '3'

services:
  wg:
    build: .
    #image: ngoduykhanh/wireguard-ui:latest
    container_name: wgui
    environment:
      - SESSION_SECRET: 1234
    ports:
      - 5000:5000
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - /etc/wireguard:/etc/wireguard
````
After a bit of trial and error I got it to work with the following configuration:
````
version: '3'

services:
  wg:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wgui
    environment:
      SESSION_SECRET: 1234
    ports:
      - 5000:5000
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - /etc/wireguard:/etc/wireguard
````
I removed the `build: .`, uncommented the `#image` and changed the variables in `evniroment`.

If it doesn't cause any other problems, I would suggest that you change the configuration to the following. Maybe this will help others as well. Thank you.
````
services:
  wg:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wgui
    environment:
      SENDGRID_API_KEY:  <Your sendgrid api key>
      EMAIL_FROM:  <The email address you registered on sendgrid>
      EMAIL_FROM_NAME:  <The sender's email address>
      SESSION_SECRET:  <Random value>
    ports:
      - 5000:5000
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - /etc/wireguard:/etc/wireguard
````

**Comment by talesam** [comment]
I tested it and a friend also tested it and it just doesn't work, it doesn't connect, I can create the user, read the QRCode, but it doesn't work, I tested 2 other projects that work. I suggest testing it before putting it to public, at least in docker.

Here is my configuration, the network at the end is that I use nginx proxy manager.

```
services:
  wg:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wgui
    cap_add:
      - NET_ADMIN
    environment:
      - SENDGRID_API_KEY=xxxxxxxxxxx
      - EMAIL_FROM=e@emial.com
      - EMAIL_FROM_NAME=e@emial.com
      - SESSION_SECRET=xxxxxxx
      - WGUI_USERNAME=admin
      - WGUI_PASSWORD=xxxxxxx
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./volumes/db:/app/db
      - ./volumes/etc/wireguard:/etc/wireguard
    ports:
      - 51820:51820/udp
    expose:
      - "5000"
    restart: always

networks:
  default:
    external:
      name: nginxproxymanager_default
```
